// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tCouponConditionList")]
public partial class TCouponConditionList
{
    [Key]
    [Column("fCouponConditionId")]
    public int FCouponConditionId { get; set; }

    [Required]
    [Column("fCouponConditionName")]
    [StringLength(50)]
    public string FCouponConditionName { get; set; }

    [Column("fTeacherId")]
    public int? FTeacherId { get; set; }

    [Column("fCourseType")]
    public bool? FCourseType { get; set; }

    [Column("fField_Id")]
    public int? FFieldId { get; set; }

    [Column("fSubjectId")]
    public int? FSubjectId { get; set; }

    [Column("fNewRegistrantOrNot")]
    public bool FNewRegistrantOrNot { get; set; }

    [Column("fBirthdayOffer")]
    public short? FBirthdayOffer { get; set; }

    [InverseProperty("FCouponCondition")]
    public virtual ICollection<TCoupon> TCoupons { get; set; } = new List<TCoupon>();
}