// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tCoursework")]
public partial class TCoursework
{
    [Key]
    [Column("fCourseworkId")]
    public int FCourseworkId { get; set; }

    [Column("fOrderDetail_Id")]
    public int FOrderDetailId { get; set; }

    [Required]
    [Column("fName")]
    [StringLength(50)]
    public string FName { get; set; }

    [Column("fDescrpition")]
    public string FDescrpition { get; set; }

    [Column("fLastModifyTime", TypeName = "datetime")]
    public DateTime FLastModifyTime { get; set; }

    [Column("fMemberId")]
    public int? FMemberId { get; set; }

    [Column("fShareAudience")]
    [StringLength(50)]
    public string FShareAudience { get; set; }

    [Column("fComment")]
    public string FComment { get; set; }

    [Column("fCommentTime", TypeName = "datetime")]
    public DateTime? FCommentTime { get; set; }

    [ForeignKey("FOrderDetailId")]
    [InverseProperty("TCourseworks")]
    public virtual TOrderDetail FOrderDetail { get; set; }

    [InverseProperty("FCoursework")]
    public virtual ICollection<TCourseworkFile> TCourseworkFiles { get; set; } = new List<TCourseworkFile>();
}