// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tLessonEvaluation")]
public partial class TLessonEvaluation
{
    [Key]
    [Column("fLessonEval_Id")]
    public int FLessonEvalId { get; set; }

    [Column("fMemberId")]
    public int FMemberId { get; set; }

    [Column("fOrderDetail_Id")]
    public int FOrderDetailId { get; set; }

    [Column("fScore")]
    public int FScore { get; set; }

    [Column("fComment")]
    [StringLength(200)]
    public string FComment { get; set; }

    [Column("fCommentDate", TypeName = "datetime")]
    public DateTime FCommentDate { get; set; }

    [Column("fCommentUpdateDate", TypeName = "datetime")]
    public DateTime? FCommentUpdateDate { get; set; }

    [Column("fDisplayStatus")]
    public bool FDisplayStatus { get; set; }

    [ForeignKey("FMemberId")]
    [InverseProperty("TLessonEvaluations")]
    public virtual TMember FMember { get; set; }

    [ForeignKey("FOrderDetailId")]
    [InverseProperty("TLessonEvaluations")]
    public virtual TOrderDetail FOrderDetail { get; set; }
}