// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tMemberCitiesList")]
public partial class TMemberCitiesList
{
    [Key]
    [Column("fMCitiesId")]
    public int FMcitiesId { get; set; }

    [Column("fMemberId")]
    public int FMemberId { get; set; }

    [Column("fCityId")]
    public int FCityId { get; set; }

    [ForeignKey("FCityId")]
    [InverseProperty("TMemberCitiesLists")]
    public virtual TCity FCity { get; set; }

    [ForeignKey("FMemberId")]
    [InverseProperty("TMemberCitiesLists")]
    public virtual TMember FMember { get; set; }
}