// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tOrderDetail")]
public partial class TOrderDetail
{
    [Column("fOrderId")]
    public int FOrderId { get; set; }

    [Key]
    [Column("fOrderDetail_Id")]
    public int FOrderDetailId { get; set; }

    [Column("fLessonCourseId")]
    public int FLessonCourseId { get; set; }

    [Column("fLessonPrice", TypeName = "money")]
    public decimal FLessonPrice { get; set; }

    [Column("fDiscount", TypeName = "money")]
    public decimal FDiscount { get; set; }

    [Column("fOrderValid")]
    public bool FOrderValid { get; set; }

    [Column("fModificationDescription")]
    [StringLength(50)]
    public string FModificationDescription { get; set; }

    [ForeignKey("FLessonCourseId")]
    [InverseProperty("TOrderDetails")]
    public virtual TLessonCourse FLessonCourse { get; set; }

    [ForeignKey("FOrderId")]
    [InverseProperty("TOrderDetails")]
    public virtual TOrder FOrder { get; set; }

    [InverseProperty("FOrderDetail")]
    public virtual ICollection<TCoursework> TCourseworks { get; set; } = new List<TCoursework>();

    [InverseProperty("FOrderDetail")]
    public virtual ICollection<TLessonEvaluation> TLessonEvaluations { get; set; } = new List<TLessonEvaluation>();
}