// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tOrder")]
public partial class TOrder
{
    [Key]
    [Column("fOrderId")]
    public int FOrderId { get; set; }

    [Column("fMemberId")]
    public int FMemberId { get; set; }

    [Column("fOrderDate", TypeName = "datetime")]
    public DateTime FOrderDate { get; set; }

    [Column("fCouponId")]
    public int? FCouponId { get; set; }

    [Required]
    [Column("fPaymentMethod")]
    [StringLength(50)]
    public string FPaymentMethod { get; set; }

    [ForeignKey("FMemberId")]
    [InverseProperty("TOrders")]
    public virtual TMember FMember { get; set; }

    [InverseProperty("FOrder")]
    public virtual ICollection<TOrderDetail> TOrderDetails { get; set; } = new List<TOrderDetail>();
}