// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tTeacher")]
public partial class TTeacher
{
    [Column("fMemberId")]
    public int FMemberId { get; set; }

    [Key]
    [Column("fTeacherId")]
    public int FTeacherId { get; set; }

    [Required]
    [Column("fTeacherName")]
    [StringLength(50)]
    public string FTeacherName { get; set; }

    [Column("fJoinDatetime", TypeName = "datetime")]
    public DateTime FJoinDatetime { get; set; }

    [Column("fTeacherProfilePic")]
    public byte[] FTeacherProfilePic { get; set; }

    [Column("fIntroduction")]
    [StringLength(300)]
    public string FIntroduction { get; set; }

    [Column("fContactInfo")]
    [StringLength(50)]
    public string FContactInfo { get; set; }

    [Column("fNote")]
    [StringLength(50)]
    public string FNote { get; set; }

    [ForeignKey("FMemberId")]
    [InverseProperty("TTeachers")]
    public virtual TMember FMember { get; set; }

    [InverseProperty("FTeacher")]
    public virtual ICollection<TChatRoomTeacher> TChatRoomTeachers { get; set; } = new List<TChatRoomTeacher>();

    [InverseProperty("FTeacher")]
    public virtual ICollection<TLessonCourse> TLessonCourses { get; set; } = new List<TLessonCourse>();

    [InverseProperty("FTeacher")]
    public virtual ICollection<TMemberFavTeacher> TMemberFavTeachers { get; set; } = new List<TMemberFavTeacher>();

    [InverseProperty("FTeacher")]
    public virtual ICollection<TTeacherImage> TTeacherImages { get; set; } = new List<TTeacherImage>();

    [InverseProperty("FTeacher")]
    public virtual ICollection<TTeacherSubject> TTeacherSubjects { get; set; } = new List<TTeacherSubject>();
}