// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tTeacherApplyLog")]
public partial class TTeacherApplyLog
{
    [Key]
    [Column("fApplyLogId")]
    public int FApplyLogId { get; set; }

    [Column("fApplyDatetime", TypeName = "datetime")]
    public DateTime FApplyDatetime { get; set; }

    [Column("fMemberId")]
    public int FMemberId { get; set; }

    [Required]
    [Column("fTeacherName")]
    [StringLength(50)]
    public string FTeacherName { get; set; }

    [Required]
    [Column("fRealName")]
    [StringLength(50)]
    public string FRealName { get; set; }

    [Required]
    [Column("fContactInfo")]
    [StringLength(50)]
    public string FContactInfo { get; set; }

    [Column("fIntroduction")]
    [StringLength(200)]
    public string FIntroduction { get; set; }

    [Column("fReason")]
    [StringLength(200)]
    public string FReason { get; set; }

    [Column("fPdfLink")]
    [StringLength(100)]
    public string FPdfLink { get; set; }

    [Column("fTeacherPlanLink")]
    [StringLength(100)]
    public string FTeacherPlanLink { get; set; }

    [Column("fProgressStatus")]
    [StringLength(50)]
    public string FProgressStatus { get; set; }

    [Column("fReviewResult")]
    public bool? FReviewResult { get; set; }

    [Column("fReviewDatetime", TypeName = "datetime")]
    public DateTime? FReviewDatetime { get; set; }

    [Column("fEmployeeId")]
    public int? FEmployeeId { get; set; }

    [Column("fNote")]
    [StringLength(50)]
    public string FNote { get; set; }

    [ForeignKey("FMemberId")]
    [InverseProperty("TTeacherApplyLogs")]
    public virtual TMember FMember { get; set; }
}