// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FinalGroupMVCPrj.Models;

[Table("tVideoCourse")]
public partial class TVideoCourse
{
    [Key]
    [Column("fVideoCourseId")]
    public int FVideoCourseId { get; set; }

    [Column("fSubjectId")]
    public int FSubjectId { get; set; }

    [Column("fCode")]
    [StringLength(20)]
    public string FCode { get; set; }

    [Column("fTeacherId")]
    public int FTeacherId { get; set; }

    [Column("fName")]
    [StringLength(50)]
    public string FName { get; set; }

    [Column("fDescription")]
    [StringLength(500)]
    public string FDescription { get; set; }

    [Column("fRequirement")]
    [StringLength(200)]
    public string FRequirement { get; set; }

    [Column("fCoursePhoto")]
    public byte[] FCoursePhoto { get; set; }

    [Column("fPrice", TypeName = "money")]
    public decimal? FPrice { get; set; }

    [Required]
    [Column("fHomeworkDescription")]
    [StringLength(200)]
    public string FHomeworkDescription { get; set; }

    [Column("fValidate")]
    [StringLength(10)]
    public string FValidate { get; set; }

    [Column("fLaunchStatus")]
    public bool FLaunchStatus { get; set; }

    [Column("fUploadDate", TypeName = "datetime")]
    public DateTime? FUploadDate { get; set; }

    [Column("fNote")]
    [StringLength(10)]
    public string FNote { get; set; }

    [Column("fUpdateDate", TypeName = "datetime")]
    public DateTime? FUpdateDate { get; set; }
}